#!/bin/sh +x

event=cache-misses
out=benchresults-cache.csv

function run_perf() {
    echo "-- running $1" >&2
    perf stat -e $event go test -bench $1\$ 2>&1 | awk "/$event/ { print \$1 }"
}

if [ -e $out ]; then
    mv $out $out.$(date +%s)
fi

echo 'Elements,Map,Slice' > $out
for cnt in 100 1000 10000 100000 1000000 10000000 100000000; do
    echo "-- running for $cnt"
    slice=$(run_perf BenchmarkSlice$cnt)
    map=$(run_perf BenchmarkMap$cnt)
    echo "$cnt,$map,$slice" >> $out
done
